In [1]:
import numpy as np
import  pandas as pd

In [3]:
df = pd.read_csv('./Dataset/Date.csv')

In [7]:
df.sample(5)

           date  product_id  city_id  orders
498  2018-08-07        3508       28       1
998  2019-03-03        1503       21       2
201  2019-04-06        2357       14     104
431  2019-09-13        5012       13       3
3    2019-08-17        7292       25       1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [43]:
df['date'] = pd.to_datetime(df['date'])

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
 4   Date        1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3)
memory usage: 39.2 KB

In [47]:
df['Year'] = df['Date'].dt.year

In [49]:
df.head()

        date  product_id  city_id  orders       Date  Year
0 2019-12-10        5628       25       3 2019-12-10  2019
1 2018-08-15        3646       14     157 2018-08-15  2018
2 2018-10-23        1859       25       1 2018-10-23  2018
3 2019-08-17        7292       25       1 2019-08-17  2019
4 2019-01-06        4344       25       3 2019-01-06  2019

In [65]:
df['Month_Number'] = df['Date'].dt.month
df.head()

        date  product_id  city_id  orders       Date  Year  Month_Number
0 2019-12-10        5628       25       3 2019-12-10     1            12
1 2018-08-15        3646       14     157 2018-08-15     2             8
2 2018-10-23        1859       25       1 2018-10-23     1            10
3 2019-08-17        7292       25       1 2019-08-17     5             8
4 2019-01-06        4344       25       3 2019-01-06     6             1

In [67]:
df['Month_Name'] = df['Date'].dt.month_name()
df.head()

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name
0,2019-12-10,5628,25,3,2019-12-10,1,12,December
1,2018-08-15,3646,14,157,2018-08-15,2,8,August
2,2018-10-23,1859,25,1,2018-10-23,1,10,October
3,2019-08-17,7292,25,1,2019-08-17,5,8,August
4,2019-01-06,4344,25,3,2019-01-06,6,1,January

In [69]:
df['Day_of_Week'] = df['Date'].dt.dayofweek
df.head()

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week
0,2019-12-10,5628,25,3,2019-12-10,1,12,December,1
1,2018-08-15,3646,14,157,2018-08-15,2,8,August,2
2,2018-10-23,1859,25,1,2018-10-23,1,10,October,1
3,2019-08-17,7292,25,1,2019-08-17,5,8,August,5
4,2019-01-06,4344,25,3,2019-01-06,6,1,January,6

In [71]:
df['day'] = df['Date'].dt.day
df.head()

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week,day
0,2019-12-10,5628,25,3,2019-12-10,1,12,December,1,10
1,2018-08-15,3646,14,157,2018-08-15,2,8,August,2,15
2,2018-10-23,1859,25,1,2018-10-23,1,10,October,1,23
3,2019-08-17,7292,25,1,2019-08-17,5,8,August,5,17
4,2019-01-06,4344,25,3,2019-01-06,6,1,January,6,6

In [75]:
df['day_name'] = df['Date'].dt.day_name()
df.head()

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week,day,day_name
0,2019-12-10,5628,25,3,2019-12-10,1,12,December,1,10,Tuesday
1,2018-08-15,3646,14,157,2018-08-15,2,8,August,2,15,Wednesday
2,2018-10-23,1859,25,1,2018-10-23,1,10,October,1,23,Tuesday
3,2019-08-17,7292,25,1,2019-08-17,5,8,August,5,17,Saturday
4,2019-01-06,4344,25,3,2019-01-06,6,1,January,6,6,Sunday

In [79]:

# is weekend?

df['date_is_weekend'] = np.where(df['day_name'].isin(['Sunday', 'Saturday']), 1,0)
df.drop(columns=['product_id','city_id','orders']).head()

,date,Date,Year,Month_Number,Month_Name,Day_of_Week,day,day_name,date_is_weekend
0,2019-12-10,2019-12-10,1,12,December,1,10,Tuesday,0
1,2018-08-15,2018-08-15,2,8,August,2,15,Wednesday,0
2,2018-10-23,2018-10-23,1,10,October,1,23,Tuesday,0
3,2019-08-17,2019-08-17,5,8,August,5,17,Saturday,1
4,2019-01-06,2019-01-06,6,1,January,6,6,Sunday,1

In [97]:
df['date_time_local'] = df['Date'].dt.timetz
df.head()

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week,day,day_name,date_is_weekend,date_week,date_time_local
0,2019-12-10,5628,25,3,2019-12-10,1,12,December,1,10,Tuesday,0,00:00:00,00:00:00
1,2018-08-15,3646,14,157,2018-08-15,2,8,August,2,15,Wednesday,0,00:00:00,00:00:00
2,2018-10-23,1859,25,1,2018-10-23,1,10,October,1,23,Tuesday,0,00:00:00,00:00:00
3,2019-08-17,7292,25,1,2019-08-17,5,8,August,5,17,Saturday,1,00:00:00,00:00:00
4,2019-01-06,4344,25,3,2019-01-06,6,1,January,6,6,Sunday,1,00:00:00,00:00:00

In [93]:
idx = pd.date_range(start = "2025-09-20", freq = "D", periods = 4)
idx.isocalendar()

            year  week  day
2025-09-20  2025    38    6
2025-09-21  2025    38    7
2025-09-22  2025    39    1
2025-09-23  2025    39    2

In [107]:
df['day_of_year'] = df['Date'].dt.dayofweek
df.sample(5)

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week,day,day_name,date_is_weekend,date_week,date_time_local,day_of_year,quarter
616,2019-02-09,5733,25,2,2019-02-09,5,2,February,5,9,Saturday,1,00:00:00,00:00:00,5,1
424,2019-10-12,637,26,1,2019-10-12,5,10,October,5,12,Saturday,1,00:00:00,00:00:00,5,4
148,2019-12-10,561,13,1,2019-12-10,1,12,December,1,10,Tuesday,0,00:00:00,00:00:00,1,4
786,2018-08-21,888,20,6,2018-08-21,1,8,August,1,21,Tuesday,0,00:00:00,00:00:00,1,3
465,2018-09-13,6566,18,8,2018-09-13,3,9,September,3,13,Thursday,0,00:00:00,00:00:00,3,3

In [109]:
df['quarter'] = df['Date'].dt.quarter
df.sample(5)

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week,day,day_name,date_is_weekend,date_week,date_time_local,day_of_year,quarter
266,2019-12-11,972,13,1,2019-12-11,2,12,December,2,11,Wednesday,0,00:00:00,00:00:00,2,4
498,2018-08-07,3508,28,1,2018-08-07,1,8,August,1,7,Tuesday,0,00:00:00,00:00:00,1,3
844,2019-04-03,4635,22,5,2019-04-03,2,4,April,2,3,Wednesday,0,00:00:00,00:00:00,2,2
902,2019-03-24,5031,0,6,2019-03-24,6,3,March,6,24,Sunday,1,00:00:00,00:00:00,6,1
341,2019-05-04,1097,26,17,2019-05-04,5,5,May,5,4,Saturday,1,00:00:00,00:00:00,5,2

In [111]:
df['is_leap_year'] = df['Date'].dt.is_leap_year
df.sample(5)

,date,product_id,city_id,orders,Date,Year,Month_Number,Month_Name,Day_of_Week,day,day_name,date_is_weekend,date_week,date_time_local,day_of_year,quarter,is_leap_year
118,2019-03-12,2251,9,1,2019-03-12,1,3,March,1,12,Tuesday,0,00:00:00,00:00:00,1,1,False
882,2019-10-14,5666,25,2,2019-10-14,0,10,October,0,14,Monday,0,00:00:00,00:00:00,0,4,False
206,2019-04-24,6082,9,1,2019-04-24,2,4,April,2,24,Wednesday,0,00:00:00,00:00:00,2,2,False
360,2019-03-23,435,7,2,2019-03-23,5,3,March,5,23,Saturday,1,00:00:00,00:00:00,5,1,False
569,2019-02-18,5795,14,4,2019-02-18,0,2,February,0,18,Monday,0,00:00:00,00:00:00,0,1,False