Install Libraries

In [2]:
import numpy as np
import pandas as pd

<heading><bold>1st Method<bold><heading>

In [5]:
df = pd.read_csv('./Dataset/placement.csv')

In [7]:
df.head(2)

   cgpa  package
0  6.89     3.26
1  5.12     1.98

<heading><bold>2nd Method<bold><heading>

In [10]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/S.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data).head(2)

   Country  Region
0  Algeria  AFRICA
1   Angola  AFRICA

<heading><bold>3rd Method<bold><heading>

In [13]:
pd.read_csv('./Dataset/file.tsv').head(2)

    0\t50\t5\t881250949
0  0\t172\t5\t881250949
1  0\t133\t1\t881250949

In [15]:
pd.read_csv('./Dataset/file.tsv',sep ='\t',names = ['zero','randome_no','fix_no.','same_no']).head(2)

   zero  randome_no  fix_no.    same_no
0     0          50        5  881250949
1     0         172        5  881250949

In [17]:
pd.read_csv('./Dataset/placement.csv', index_col = 'cgpa').head(2)

      package
cgpa
6.89     3.26
5.12     1.98

In [19]:
pd.read_csv('./Dataset/placement.csv', header = 1).head(2)

   6.89  3.26
0  5.12  1.98
1  7.82  3.25

In [21]:
pd.read_csv('./Dataset/placement.csv', usecols = ['cgpa']).head(2)

   cgpa
0  6.89
1  5.12

In [23]:
pd.read_csv('./Dataset/placement.csv', usecols = ['cgpa'], squeeze = True).head(2)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [ ]:
pd.read_csv('./Dataset/placement.csv', skiprows = [1,2]).head(5)

In [ ]:
pd.read_csv('./Dataset/placement.csv', nrows = 10)

In [27]:
pd.read_csv('./Dataset/placement.csv', nrows = 10)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57
5  7.89     2.99
6  6.73     2.60
7  6.75     2.48
8  6.09     2.31
9  8.31     3.51

In [29]:
#Encoding Parameter

In [33]:
#skip bad lines
pd.read_csv('./Dataset/placement.csv', on_bad_lines='skip')

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [40]:
#dtypes parameter
# pd.read_csv('./Dataset/placement.csv', dtype = {'package':int})

In [52]:
#Handling Dates
pd.read_csv('./Dataset/matches.csv', parse_dates = ['date']).head(2)
#converted date column from Object -----> Date Time 64

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [66]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [68]:
rename("Royal Challengers Bangalore")

'RCB'

In [76]:
#convertors
pd.read_csv('./Dataset/matches.csv', converters = {'team2': rename}).head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,RCB,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN

In [80]:
#na_values parameters:
pd.read_csv('./Dataset/matches.csv', na_values = ['umpire3']).head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN

In [ ]:
#loading huge data in chunks:
chunksize = 5000