In [79]:
import numpy as np
import pandas as pd
import warnings
warnings.simplefilter("ignore", UserWarning)

In [80]:
df = pd.read_csv('./Dataset/iris.csv')

In [81]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [82]:
from sklearn.preprocessing import LabelEncoder

In [83]:
enc = LabelEncoder()

In [84]:
df['species'] = enc.fit_transform(df['species'])

In [85]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [86]:
df = df[df['species'] != 0] [['sepal_width','petal_length','species']]

In [87]:
df.head()

    sepal_width  petal_length  species
50          3.2           4.7        1
51          3.2           4.5        1
52          3.1           4.9        1
53          2.3           4.0        1
54          2.8           4.6        1

In [88]:
df = df.sample(100)
df_train = df.iloc[:60,:].sample(10) #random 10 training data
df_val = df.iloc[60:80,:].sample(5) #random 5 validation data
df_test = df.iloc[80:,:].sample(5) #random 5 test data

In [89]:
X_test = df_val.iloc[:,0:2].values
y_test = df_val.iloc[:,-1].values

In [90]:
df_bagging = df_train.sample(7, replace = True)
X = df_bagging.iloc[:,0:2]
y = df_bagging.iloc[:,-1]

In [91]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from mlxtend.plotting import plot_decision_regions
from sklearn.metrics import accuracy_score

In [92]:
dt_bagging1 = DecisionTreeClassifier()

In [93]:
dt_bagging1.fit(X, y)
y_pred = dt_bagging1.predict(X_test)
print(accuracy_score(y_test, y_pred))

1.0

In [94]:
models = []
accuracies = []

for i in range(7):

    # Bootstrap sample
    sample = df_train.sample(7, replace=True)

    X_train = sample.iloc[:,0:2]
    y_train = sample.iloc[:,-1]

    model = DecisionTreeClassifier(random_state=i)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    print(f"Tree {i+1} Accuracy = {acc:.2f}")

    models.append(model)
    accuracies.append(acc)

Tree 1 Accuracy = 0.60
Tree 2 Accuracy = 0.60
Tree 3 Accuracy = 0.80
Tree 4 Accuracy = 1.00
Tree 5 Accuracy = 1.00
Tree 6 Accuracy = 1.00
Tree 7 Accuracy = 0.40

In [95]:
query = np.array([2.2, 5.0]).reshape(1, 2)

for i, model in enumerate(models):
    print(f"Tree {i+1}:", model.predict(query))

Tree 1: [1]
Tree 2: [1]
Tree 3: [1]
Tree 4: [1]
Tree 5: [2]
Tree 6: [2]
Tree 7: [1]